OBJS=main.obj pipe.obj
BIN=injectdll.exe
PDB=injectdll.pdb

CFLAGS=/nologo /O2 /W4 /wd4054 /wd4055 /MTd /GS /Zi

LDFLAGS=/nologo /DEBUG /DYNAMICBASE /NXCOMPAT /PDB:$(PDB) \
	/WX /MACHINE:X64 /DEFAULTLIB:Psapi.lib /DEFAULTLIB:Shlwapi.lib \
	/DEFAULTLIB:Advapi32.lib

$(BIN): $(OBJS)
	link $(OBJS) /OUT:$(BIN) $(LDFLAGS)

clean:
	del /F *.ilk *.obj *.exe *.pdb

